### ISSUE TITLE
Integrate "FireMonkey Migration Assistant" features

### ISSUE THREAD

**Issue by LaKraven** [LaKraven/MonkeyMixer#2]
Going to be implementing the "FireMonkey Migration Assistant" features from the project formerly known as "MonkeyMixer" into the open-source MonkeyMixer codebase.

This will add automated VCL to FMX conversion which works for a majority of existing VCL forms, and will help developers migrate more quickly.
Forms which cannot be automatically converted will be reported and left in as VCL forms so that the developer can decide how best to handle them.

**Comment by LK-Simon** [comment]
As I no longer have Delphi, this feature will no longer be achievable.
