### ISSUE TITLE
10.2 Tokyo

### ISSUE THREAD

**Issue by dimka11** [LaKraven/MonkeyMixer#4]
Please add support for Delphi 10.2 Tokyo.

**Comment by dtamade** [comment]
Please

**Comment by amarildolacerda** [comment]
I submit a Pull Request with DPR for Tokyo

**Comment by LK-Simon** [comment]
Better late than never, I suppose, but I have incorporated @amarildolacerda’s pull request today as part of my “closing out” of Delphi projects (I no longer have any Delphi licenses)
