### ISSUE TITLE
Can the main app be Firemonkey, with vcl form?

### ISSUE THREAD

**Issue by z505** [LaKraven/MonkeyMixer#5]
Can one develop an entire app in Firemonkey, then just have a vcl form loaded into the firemonkey app? Or is this designed the other way around: for a vcl app to embed firemonkey?

Would be nice to write a major app all in firemonkey, but then if a vcl form is needed on Windows, load it, and on macos, load firemonkey form. There are some things in vcl that render much better on windows, but to have the main application in firemonkey is good, just loading vcl when absolutely neccesary on Windows only

**Comment by EndErr** [comment]
I can confirm that it is possible

**Comment by z505** [comment]
Interesting, I am wondering how two copies of different gui states are loaded... Like application object, if two application objects are used or just one.. Seems risky, but powerful if it works. Also, no way to put a vcl window into a firemonkey tpanel, unless SetParent used?

**Comment by djjd47130** [comment]
I would imagine this would still restrict you from going to any other platform than Windows. I wouldn't expect a VCL form to work on, say, Android for example - not without some sort of "fake" WinAPI.

**Comment by LK-Simon** [comment]
Your initial application can be either VCL or FireMonkey.... but be aware that the use of ANY VCL within the application will mean you cannot build for other target platforms.
